added Device Trait "Cook"
ioBroker/ioBroker.iot pull request #417
Opened 2022-05-10 21:35 UTC by GreatSUN

added Device Trait Cook to support emulating "intelligent coffee machines" as well.

2022-05-11 16:07 UTC, Apollon77 requested changes

2022-05-11 16:07 UTC, Apollon77 commented on io-package.json
> +    "version": "1.11.5",
Please do not increase version and do not add news entries (especially not empty ones!!) ... this is done by release script based on redme changelog entries

2022-05-11 16:07 UTC, Apollon77 commented on src/src/Tabs/Options.js
> +                <Button variant="outlined" size="small" color="primary" style={{textAlign: 'center'}} onClick={() => { openAmazonReviewUrl() }}>{I18n.t('Review')}</Button>
what does this change do ? Code is basically the same??!

2022-05-11 16:07 UTC, Apollon77 commented on io-package.json
> +    "version": "1.11.5",
SO please add a new README changelog entry

2022-05-19 11:34 UTC, closed without merging

2022-05-19 11:35 UTC, GreatSUN commented
Need to get rid of some stuff and redo changes properly ;-)

Sorry!